cat > docker-compose.yml <<'EOF'
version: '3.8'

services:
  directus:
    build: .
    container_name: secure-directus
    restart: unless-stopped
    ports:
      - "8055:8055"
    volumes:
      - directus-database:/directus/database
      - directus-uploads:/directus/uploads
      - directus-extensions:/directus/extensions
      - directus-templates:/directus/templates
    environment:
      KEY: ${SERVICE_BASE64_64_KEY}
      SECRET: ${SERVICE_BASE64_64_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@example.com}
      ADMIN_PASSWORD: ${SERVICE_PASSWORD_ADMIN}
      DB_CLIENT: sqlite3
      DB_FILENAME: /directus/database/data.db
      WEBSOCKETS_ENABLED: true
      RATE_LIMITER_ENABLED: true
      RATE_LIMITER_POINTS: 50
      RATE_LIMITER_DURATION: 1
      SECURITY_SESSION_SECURE: true
      SECURITY_SESSION_SAME_SITE: strict
      SECURITY_CSP: "default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'"
      CORS_ENABLED: true
      CORS_ORIGIN: ${CORS_ORIGIN}
      CORS_METHODS: GET,POST,PATCH,DELETE
      CORS_ALLOWED_HEADERS: Content-Type,Authorization
      CORS_EXPOSED_HEADERS: Content-Range
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8055/admin/login"]
      interval: 5s
      timeout: 20s
      retries: 10

volumes:
  directus-database:
  directus-uploads:
  directus-extensions:
  directus-templates:
EOF
